# 1. QR-Factorization

In [22]:
import numpy as np

In [23]:
A = np.matrix([[3, 4],
               [1, 2]])

In [24]:
a1 = A[:,0]
a2 = A[:,1]

In [25]:
q1 = a1 / np.linalg.norm(a1)

In [26]:
a2_prime = a2 - q1 * q1.T * a2

In [27]:
q2 = a2_prime / np.linalg.norm(a2_prime)

In [28]:
Q = np.concatenate((q1, q2), axis=1)
Q

matrix([[ 0.9486833 , -0.31622777],
        [ 0.31622777,  0.9486833 ]])

In [29]:
R = np.matrix([[np.linalg.norm(a1), np.float(q1.T*a2)],
          [0, np.linalg.norm(a2_prime)]])
R

matrix([[3.16227766, 4.42718872],
        [0.        , 0.63245553]])

In [30]:

"""확인
A
Q * Q.T
Q.T * Q
3/np.sqrt(10)
1/np.sqrt(10)
R
np.sqrt(10)
7*np.sqrt(2/5)
np.sqrt(2/5)
Q * R

"""

'확인\nA\nQ * Q.T\nQ.T * Q\n3/np.sqrt(10)\n1/np.sqrt(10)\nR\nnp.sqrt(10)\n7*np.sqrt(2/5)\nnp.sqrt(2/5)\nQ * R\n\n'

## QR in linalg

In [31]:
import scipy
from scipy import matrix
from scipy import linalg
import numpy as np

In [32]:
# Classical Gram-Schmidt orthogonalization
# MATLAB
# function [Q, R] = clgs(A)
# [m, n] = size(A);
# V=A; Q=eye(m,n);
# R=zeros(n,n);
# for j=1:n
# for i=1:j-1
# R(i,j)=Q(:,i)’*A(:,j);
# V(:,j)=V(:,j)-R(i,j)*Q(:,i);
# end
# R(j,j)=norm(V(:,j));
# Q(:,j)=V(:,j)/R(j,j);
# end

In [33]:
# Modified Gram-Schmidt orthogonalization
# MATLAB
# function [Q, R] = grams(A)
# [m, n] = size(A);
# Q = A;
# R=zeros(n,n);
# for i = 1:n-1
# R(i,i)=norm(Q(:,i));
# Q(:,i)=Q(:,i)/R(i,i);
# R(i,i+1:n)=Q(:,i)’*Q(:,i+1:n);
# Q(:,i+1:n)=Q(:,i+1:n)-Q(:,i)*R(i,i+1:n);
# end
# R(n,n)=norm(Q(:,n));
# Q(:,n)=Q(:,n)/R(n,n);

In [34]:
A = matrix([[-1, -1, 1], [1, 3, 3], [-1, -1, 5], [1, 3, 7]])

In [35]:
A

matrix([[-1, -1,  1],
        [ 1,  3,  3],
        [-1, -1,  5],
        [ 1,  3,  7]])

In [36]:
Q, R = linalg.qr(A)

In [37]:
Q = np.asmatrix(Q)
Q

matrix([[-0.5, -0.5,  0.5,  0.5],
        [ 0.5, -0.5,  0.5, -0.5],
        [-0.5, -0.5, -0.5, -0.5],
        [ 0.5, -0.5, -0.5,  0.5]])

In [38]:
R = np.asmatrix(R)
R

matrix([[ 2.,  4.,  2.],
        [ 0., -2., -8.],
        [ 0.,  0., -4.],
        [ 0.,  0.,  0.]])

In [39]:
Q*R

matrix([[-1., -1.,  1.],
        [ 1.,  3.,  3.],
        [-1., -1.,  5.],
        [ 1.,  3.,  7.]])

# 2. Eigenvalues & Eigenvectors

## Equation Solver

In [40]:
from sympy.solvers import solve
from sympy import Symbol

In [41]:
x = Symbol('x')
solve(x**2 - 1, x)

[-1, 1]

## Eigenvalues with Equation

In [42]:
A = matrix([[4, -2], [1, 1]])
A

matrix([[ 4, -2],
        [ 1,  1]])

In [43]:
lam = Symbol('lam')

In [44]:
A_lam = A - lam*np.asmatrix(np.identity(2))
A_lam

matrix([[-1.0*lam + 4, -2],
        [1, -1.0*lam + 1]], dtype=object)

In [45]:
equation = A_lam[0,0]*A_lam[1,1] - A_lam[0,1]*A_lam[1,0]
equation

(-1.0*lam + 1)*(-1.0*lam + 4) + 2

In [46]:
solve(equation, lam)

[2.00000000000000, 3.00000000000000]

## Eigenvalues and Eigenvectors with Package

# 2 x 2

In [47]:
eigenvalue, eigenvector = linalg.eig(A)

In [48]:
eigenvalue

array([3.+0.j, 2.+0.j])

In [49]:
eigenvector

array([[0.89442719, 0.70710678],
       [0.4472136 , 0.70710678]])

In [51]:
print(eigenvector[:,0] / eigenvector[0,0])

[1.  0.5]


In [52]:
print(eigenvector[:,1] / eigenvector[0,1])

[1. 1.]


# 3 x 3

In [54]:
import numpy as np
eig = np.linalg.eig

matrix = np.matrix([[2,-3,1],[1,-2,1],[1,-3,2]])
eigen = eig(matrix)

eigen_value = eigen[0]
print(eigen_value)
# [0,1,1]

eigen_vector = eigen[1]
print(eigen_vector)

print(eigen_vector[:,0] / eigen_vector[0,0])

print(eigen_vector[:,1] / eigen_vector[0,1])

print(eigen_vector[:,2] / eigen_vector[0,2])

[1.33226763e-15+0.00000000e+00j 1.00000000e+00+8.74190484e-16j
 1.00000000e+00-8.74190484e-16j]
[[-0.57735027+0.j          0.81103583+0.j          0.81103583-0.j        ]
 [-0.57735027+0.j          0.36250517-0.11591802j  0.36250517+0.11591802j]
 [-0.57735027+0.j          0.27647967-0.34775407j  0.27647967+0.34775407j]]
[[1.-0.j]
 [1.-0.j]
 [1.-0.j]]
[[1.        +0.j       ]
 [0.44696566-0.1429259j]
 [0.34089699-0.4287777j]]
[[1.        +0.j       ]
 [0.44696566+0.1429259j]
 [0.34089699+0.4287777j]]


# 3. Eigen Value Decomposition

# 예시 1

In [57]:
inv = np.linalg.inv

A = np.matrix([[4, -2], [1, 1]])


In [58]:
eigenvalue, eigen_vector = linalg.eig(A)

In [59]:
eigenvalue

array([3.+0.j, 2.+0.j])

In [60]:
eigen_vector

array([[0.89442719, 0.70710678],
       [0.4472136 , 0.70710678]])

In [61]:
inv(eigen_vector) # U^(-1)


array([[ 2.23606798, -2.23606798],
       [-1.41421356,  2.82842712]])

In [62]:
inv(eigen_vector) * A * eigen_vector # eigen value # numerical result # # U^(-1) * S * U
eigen_vector * np.matrix([[3,0],[0,2]]) * inv(eigen_vector)

matrix([[ 4., -2.],
        [ 1.,  1.]])

# 예시 2

In [20]:
eigenvalue, eigenvector = linalg.eig(A)

In [21]:
eigenvalue.shape[0]

2

In [22]:
L = np.identity(eigenvalue.shape[0])
for i in range(eigenvalue.shape[0]) :
    L[i, i] = eigenvalue[i]
L

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: ComplexWarning: Casting complex values to real discards the imaginary part
  This is separate from the ipykernel package so we can avoid doing imports until


array([[ 2.,  0.],
       [ 0., -5.]])

In [23]:
S= np.asmatrix(eigenvector)
S

matrix([[ 0.89442719, -0.31622777],
        [ 0.4472136 ,  0.9486833 ]])

In [24]:
A*S

matrix([[ 1.78885438,  1.58113883],
        [ 0.89442719, -4.74341649]])

In [25]:
S*L

matrix([[ 1.78885438,  1.58113883],
        [ 0.89442719, -4.74341649]])

In [26]:
A*S==S*L

matrix([[ True, False],
        [False,  True]])

In [27]:
np.allclose(A*S, S*L)

True