## 1. Plusol

In [1]:
import numpy as np
from scipy import linalg

In [2]:
def plusol(A, b):
    m, n = A.shape
    p, l, u = linalg.lu(A)
    
    y = np.zeros((m, 1))
    c = np.dot(p, b)
    
    for j in range(m):
        y[j] = c[j] - np.dot(l[j, :j], y[:j])
    
    x = np.zeros((n, 1))
    
    for j in range(n-1, -1, -1):
        x[j] = (y[j]-np.dot(u[j, j+1:],x[j+1:]))/u[j,j]
    
    return x

In [3]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [4]:
b = np.array([[1],[1],[1]])

In [5]:
np.dot(A, plusol(A, b))

array([[1.],
       [1.],
       [1.]])

## 2. Determinant

In [6]:
def determ(A):
    p, l, u = linalg.lu(A)
    d = linalg.det(p)*np.prod(np.diag(u))
    return d

In [7]:
determ(A)

-9.516197353929915e-16

In [8]:
linalg.det(A)

0.0

## 3. Matrix dot

In [9]:
mat1 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
mat2 = np.array([[1,2],[4,5],[7,8]])

In [10]:
np.dot(mat1, mat2)

array([[ 30,  36],
       [ 66,  81],
       [102, 126],
       [138, 171]])

In [11]:
def matrixmul(mat1, mat2):
    newmat = []
    for i in range(len(mat1)):
        newmati = []
        for k in range(len(mat2[0])):
            newmatik = 0
            for j in range(len(mat2)):
                newmatik += mat1[i][j]*mat2[j][k]
            newmati.append(newmatik)
        newmat.append(newmati)
    return newmat

In [12]:
matrixmul(mat1,mat2)

[[30, 36], [66, 81], [102, 126], [138, 171]]

In [13]:
mat1@mat2

array([[ 30,  36],
       [ 66,  81],
       [102, 126],
       [138, 171]])